---

- block:
    - name: "PreChecks"
      include_tasks: prechecks.yml
      tags: [prechecks]

    - name: "Remove images"
      include_tasks: removeimages.yml

    - name: "Pull Images."
      include_tasks: pullimages.yml

    - name: "Save images to a tar file."
      include_tasks: exportimages.yml

  become: true
