---

- name: "Login to Red Hat container Registry"
  shell: | 
         docker login -u "{{rhreg_user}}" -p "{{rhreg_pass}}" "{{rhreg_name}}"
  when:
    - rhreg_user is defined
    - rhreg_pass is defined
    - rhreg_name is defined

- name: "Pull oscp images from registry.redhat.io"
  shell: |
         docker pull "{{ item }}"
  with_items: "{{ core_oscp_images }}"
  when:
    - 'ocp_images_pull_core == "yes"'

- name: "Pull oscp application images from registry.redhat.io and docker(nexus)"
  shell: |
         docker pull "{{ item }}"
  with_items: "{{ application_oscp_images }}"
  when:
    - 'ocp_images_pull_app == "yes"'

- name: "Pull optional oscp images from registry.redhat.io"
  shell: |
         docker pull "{{ item }}"
  with_items: "{{ optional_oscp_images }}"
  when:
    - 'ocp_images_pull_opt == "yes"'


# When docker is included by default with ansible we can use these.
#- name: Pull oscp images from registry.redhat.io
#  docker_image:
#    name: "{{ item }}"
#  state: present
#  with_items: "{{ core_oscp_images }}"

#- name: Pull oscp application images from registry.redhat.io and docker(nexus)
#  docker_image:
#    name: "{{ item }}"
#    state: present
#  with_items: "{{ application_oscp_images }}"

#- name: Pull optional oscp images from registry.redhat.io
#  docker_image:
#    name: "{{ item }}"
#  state: present
#  with_items: "{{ optional_oscp_images }}"
